- Accept uploaded videos as file-like objects or bytes in backend servers.
- Use a short-lived temp file during processing (deleted afterward).
- Extract frames (in memory), detect/extract audio (in memory), call OpenAI for vision and transcription, and output a final summary.
- Provide ready-to-run examples (FastAPI, Flask, CLI) and optional Docker setup.
